# week08/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w08e1
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account
  # Example: echo -n 'myblobstorageaccount' | base64
  AZURE_STORAGE_ACCOUNT_NAME: "dmVkYW5n" 
  # Example: echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: "VHA2elRHdVJtbkJ1Y2FpQUczWFlIVVBNY3hwTHIydDA0eFJoQSswYzJnSVN1VlFwK3RYZC9OSHZCYVdGZE1tc09KdG1td25hQnVNdytBU3Q4dDFOZVE9PQ=="
